#!/bin/bash
# Swiftstack service
#

./utils.sh


env

print_log "$(env)"

cmd=$1
serviceStatus=""

if [ -n "$gitTag" ]; then
    agentSendLogMessage  "Found gitTag parameter gitTag = ${gitTag}"
else
     agentSendLogMessage  "Didn't find custom parameter gitTag. Using gitTag=master"
     gitTag="swiftstack container create"
fi

#print_log "Yum epel package install"

yum install -y epel-release

yum install -y python-pip

#sudo pip install pip --upgrade

#sudo yum install -y python-swiftclient

yum install python-setuptools
easy_install pip
pip install --upgrade setuptools
pip install python-swiftclient

# Run the Service

case $cmd in
        start)
		swift -A http://184.94.251.119/auth/v1.0 -U Bill -K harper post Bills-Dev
                serviceStatus="Started"
                ;;
        stop)   
                serviceStatus="Stopped"
                ;;
        *)
                serviceStatus="Error: Not a valid argument"
                exit 127
                ;;
esac
