#!/usr/bin/env bash
#
# Swiftstack service SS02 example using swift clients
#

yum update -y

. /utils.sh


env

print_log "$(env)"

cmd=$1
serviceStatus=""

if [ -n "$gitTag" ]; then
    agentSendLogMessage  "Found gitTag parameter gitTag = ${gitTag}"
else
     agentSendLogMessage  "Didn't find custom parameter gitTag. Using gitTag=master"
     gitTag="swiftstack container create"
fi
print_log "INVOKE - Swift Service to make a container"
#print_log "Yum epel package install"
print_log "INSTALL - Installing epl-release"
yum install -y epel-release

#yum install -y python-pip

#sudo pip install pip --upgrade

#sudo yum install -y python-swiftclient
print_log "INSTALL - Installing Python tools, Pip and his followers" 
yum install -y python-setuptools
easy_install pip
pip install --upgrade pip
pip install --upgrade setuptools
print_log "INSTALL - Installing Swift CLI package"
pip install python-swiftclient
print_log "CONTAINER NAME IS:"$CONTAINER
print_log "RUN - Now lets START and run the service"
# Run the Service

case $cmd in
        start)
		print_log "START - make a container called Bills-Dev."
		swift -A http://184.94.251.119/auth/v1.0 -U Bill -K harper post Bills-Dev
                serviceStatus="Started"
                ;;
        stop)   
                serviceStatus="Stopped"
                ;;
        *)
                serviceStatus="Error: Not a valid argument"
                exit 127
                ;;
esac
